In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [2]:
tickers = ['MNKD', 'ACRX', 'ECYT']
portfolio = pd.DataFrame()

for t in tickers:
    portfolio[t] = wb.DataReader(t, data_source='yahoo', start='2017-1-1')['Adj Close']

In [3]:
portfolio.tail()

            MNKD  ACRX  ECYT
Date
2017-10-17  4.75  1.75  4.35
2017-10-18  4.13  1.75  4.91
2017-10-19  3.96  1.75  4.97
2017-10-20  4.11  2.00  5.19
2017-10-23  3.70  2.03  4.75

In [4]:
portfolio_returns = np.log(portfolio / portfolio.shift(1))

In [5]:
portfolio_returns

                MNKD      ACRX      ECYT
Date
2017-01-03       NaN       NaN       NaN
2017-01-04  0.076373  0.038466  0.018976
2017-01-05 -0.029853  0.000000 -0.034420
2017-01-06  0.015038 -0.019048  0.038173
2017-01-09 -0.061558 -0.019418 -0.022728
2017-01-10  0.015748  0.038466  0.011429
2017-01-11 -0.015748  0.018692 -0.030772
2017-01-12  0.031253  0.036368  0.007782
2017-01-13  0.059719  0.017700 -0.003884
2017-01-17 -0.014599 -0.035718 -0.051908
2017-01-18 -0.014815  0.000000 -0.029108
2017-01-19 -0.030305 -0.018349 -0.060888
2017-01-20 -0.015504 -0.018692  0.004474
2017-01-23  0.075223 -0.019048 -0.036368
2017-01-24 -0.029414  0.000000  0.031893
2017-01-25  0.014815  0.019048  0.013363
2017-01-26  0.000000 -0.038466 -0.008889
2017-01-27 -0.014815  0.019418 -0.004474
2017-01-30 -0.045810  0.000000 -0.055314
2017-01-31  0.089612  0.019048  0.046305
2017-02-01  0.014185  0.000000 -0.022884
2017-02-02 -0.185142  0.072759  0.000000
2017-02-03 -0.034486  0.051293  0.009217
2017-02-06 -0.054067  0.032790  0.000000
2017-02-07 -0.057158 -0.032790 -0.018519
2017-02-08  0.000000 -0.033902 -0.018868
2017-02-09  0.019418  0.066691  0.051055
2017-02-10  0.000000  0.016000 -0.009091
2017-02-13  0.074108 -0.016000 -0.004577
2017-02-14 -0.036368 -0.032790 -0.037388
...              ...       ...       ...
2017-09-12  0.089052  0.015504 -0.028573
2017-09-13 -0.004494 -0.031253  0.014389
2017-09-14  0.013423 -0.048790  0.021202
2017-09-15  0.017622  0.032790 -0.014085
2017-09-18 -0.004376  0.031749  0.000000
2017-09-19 -0.121078  0.000000  0.000000
2017-09-20 -0.020001  0.000000  0.000000
2017-09-21 -0.020409  0.000000 -0.021506
2017-09-22  0.020409  0.045810  0.007220
2017-09-25 -0.015267  0.152016  0.007168
2017-09-26 -0.036558  0.085942 -0.007168
2017-09-27 -0.016086  0.034686 -0.014493
2017-09-28  0.182322 -0.011429 -0.007326
2017-09-29 -0.022780  0.055880  0.036105
2017-10-02  0.075424  0.178692  0.945643
2017-10-03  0.186586  0.000000  0.482324
2017-10-04  0.227390 -0.050337  0.036732
2017-10-05  0.337279 -0.035023 -0.067823
2017-10-06  0.014014  0.009852  0.008734
2017-10-09  0.057931  0.019418 -0.102466
2017-10-10  0.230248  0.056089  0.005764
2017-10-11 -0.204320 -0.027652 -0.077651
2017-10-12  0.000000 -0.911629  0.004132
2017-10-13 -0.035353 -0.009346 -0.111104
2017-10-16  0.026170 -0.088293 -0.006936
2017-10-17 -0.131951 -0.108214  0.009238
2017-10-18 -0.139867  0.000000  0.121098
2017-10-19 -0.042033  0.000000  0.012146
2017-10-20  0.037179  0.133531  0.043314
2017-10-23 -0.105090  0.014889 -0.088589

[204 rows x 3 columns]

In [7]:
# Calculate the mean of security daily returns
MNKD_Mean_d = portfolio_returns['MNKD'].mean()
ECYT_Mean_d = portfolio_returns['ECYT'].mean()
ACRX_Mean_d = portfolio_returns['ACRX'].mean()

In [8]:
# Calculate the mean of security annual returns
MNKD_Mean_a = portfolio_returns['MNKD'].mean() * 250
ECYT_Mean_a = portfolio_returns['ECYT'].mean() * 250
ACRX_Mean_a = portfolio_returns['ACRX'].mean() * 250

In [9]:
# Calculate the standard deviation of daily security returns
MNKD_STD_d = portfolio_returns['MNKD'].std()
ECYT_STD_d = portfolio_returns['ECYT'].std()
ACRX_STD_d = portfolio_returns['ACRX'].std()

In [ ]:
# Calculate the standard deviation of annual security returns
MNKD_STD_d = portfolio_returns['MNKD'].std() * 250 ** 0.5
ECYT_STD_d = portfolio_returns['ECYT'].std() * 250 ** 0.5
ACRX_STD_d = portfolio_returns['ACRX'].std() * 250 ** 0.5